version: "3.8"

services:
  server:
    build:
      context: ./server
    volumes:
      - ./server:/app
    working_dir: /app
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 8000:80

  client:
    build:
      context: ./client
    volumes:
      - ./client:/app
    environment:
      - REACT_APP_PROXY_TARGET=http://server
    ports:
      - 3000:80
