version: "3.8"

services:
  db:
    image: postgres:13.3
    environment:
      - POSTGRES_USER=capu
      - POSTGRES_PASSWORD=capu
      - POSTGRES_DB=capu

  admin:
    image: adminer
    ports:
      - 8080:8080

  server:
    build:
      context: ./server
    volumes:
      - ./server:/app
    working_dir: /app
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 8000:80

  client:
    build:
      context: ./client
    volumes:
      - ./client:/app
    environment:
      - REACT_APP_PROXY_TARGET=http://server
    ports:
      - 3000:80
